<script type="text/javascript">
    //Status off
    $('.ston').live('click',function()
    {
        var offId = $(this).attr('id'); 
        
        $.ajax({
            type:"POST",
            url:"/admin/employee/statusOff",
            cache:false,
            data:{ offId:offId },
            dataType:"html",
            success:function(data)
            {
                $("#msg").html(data);
                location.reload();
            }
        });

    });

    //Status On
    $('.stof').live('click',function()
    {
        var onId = $(this).attr('id'); 
        
        $.ajax({
            type:"POST",
            url:"/admin/employee/statusOn",
            cache:false,
            data:{ onId:onId },
            dataType:"html",
            success:function(data)
            {
                $("#msg").html(data);
                location.reload();
                
            }
        });

    });
    function isNumber(evt)
    {
        evt = (evt) ? evt : window.event;
        var charCode = (evt.which) ? evt.which : evt.keyCode;
        if (charCode > 31 && (charCode < 48 || charCode > 57))
        {
            alert("Only Numbers");
            return false;
        }
        return true;
    }
</script>
<div class="span9" id="content">
    <div class="row-fluid">
        <div class="span12">

            <!-- block - -->

            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Employee Form</div>
                    <span style="font-size:12px;color:red; margin-left:520px; float:left;">
                        <div id="msg"></div>
                        <?php
                        if(count($flashMessages))
                        {
                            foreach ($flashMessages as $msg)
                            {
                                echo "<br>".$msg;   
                            }   
                        }
                        ?>
                    </span>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <form class="form-horizontal" id="addCategory" name="addCategory" method="post" enctype="multipart/form-data">
                            <fieldset>
                                <legend>Form Components</legend>
                               
                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Name</label>
                                    <div class="controls">
                                        <input type="text" name="name" id="name" class="span6" required >
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Designation</label>
                                    <div class="controls">
                                        <input type="text" name="designation" id="designation" class="span6" required >
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Salary</label>
                                    <div class="controls">
                                        <input type="text" name="salary" id="salary" class="span6" onkeypress="return isNumber(event)" required >
                                    </div>
                                </div>

                                <div class="form-actions">
                                    <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                    <button type="reset" class="btn" id="cancel">Cancel</button>
                                </div>
                            </fieldset>
                        </form>
                        
                    </div>
                </div>
                <div class="navbar navbar-inner block-header">
                    <div class="block-content collapse in">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Name</th>
                                    <th>Designation</th>
                                    <th>Salary</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                        <tbody>
                    <?php
                    $cnt= count($fetchAllDatas);
                    foreach ($fetchAllDatas as $key => $value)
                    {
                    ?>                         
    	                <tr>
                            <td><?php echo $value['id'];?></td>
                            <td><?php echo $value['name']; ?></td>
                            <td><?php echo $value['designation']; ?></td>
                            <td><?php echo $value['salary']; ?></td>
    	                    <td><?php 
                            
                                if($value['status'] == 1)
                                {
                                ?>
                                    <img src="/images/on.png" border="0" width="20" height="20" id="<?php echo $value['id']; ?>" class="ston">
                                <?php
                                }
                                else 
                                {
                                    ?>
                                    <img src="/images/off.png" border="0" width="20" height="20" id="<?php echo $value['id']; ?>" class="stof">
                                    <?php
                                }
                                ?>
                            </td>
    	                    
    	                    <td>
    	                    	<a href="/admin/employee/edit/<?php echo $value['id']; ?>" style="text-decoration:none;"><img src="/images/edit.png" border="0" width="20" height="20"></a>
    	                    </td>
                            <!--<td>
                                <img src="/images/delete.png" id="<?php echo $value['id']; ?>" border="0" width="20" height="20" class="del" />
                            </td>-->
    	                </tr>
                    <?php
                    }
                    ?>
                        <tr><td colspan="6">
                    <div align="center"><?php echo $this->paginationControl($this->fetchAllDatas, 'Elastic', 'pagination.phtml'); ?></div></td></tr>
            </tbody>
            </table>
        </div>
                    
                </div>
            </div>


        </div>

    </div>

</div>
</div>
<script type="text/javascript">
    $("#cancel").click(function()
    {
        window.location.href= "<?php echo $this->basePath()?>/admin/employee/add";
    });

</script>