<script type="text/javascript">
    
    function isNumber(evt)
    {
        evt = (evt) ? evt : window.event;
        var charCode = (evt.which) ? evt.which : evt.keyCode;
        if (charCode > 31 && (charCode < 48 || charCode > 57))
        {
            alert("Only Numbers");
            return false;
        }
        return true;
    }
</script>
<div class="span9" id="content">
    <div class="row-fluid">
        <div class="span12">

            <!-- block - -->

            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Employee Form</div>
                    <span style="font-size:12px;color:red; margin-left:520px; float:left;">
                        <div id="msg"></div>
                        <?php
                        if(count($flashMessages))
                        {
                            foreach ($flashMessages as $msg)
                            {
                                echo "<br>".$msg;   
                            }   
                        }
                        ?>
                    </span>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <?php
                        foreach ($editData as $value)
                        {
                        ?>
                        <form class="form-horizontal" id="addCategory" name="addCategory" method="post" enctype="multipart/form-data">
                            <fieldset>
                                <legend>Form Components</legend>
                               
                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Name</label>
                                    <div class="controls">
                                        <input type="text" name="name" id="name" class="span6" value="<?php echo $value['name']?>" required >
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Designation</label>
                                    <div class="controls">
                                        <input type="text" name="designation" id="designation" value="<?php echo $value['designation']?>" class="span6" required >
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Salary</label>
                                    <div class="controls">
                                        <input type="text" name="salary" id="salary" class="span6" value="<?php echo $value['salary']?>" onkeypress="return isNumber(event)" required >
                                    </div>
                                </div>

                                <div class="form-actions">
                                    <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                    <button type="reset" class="btn" id="cancel">Cancel</button>
                                </div>
                            </fieldset>
                        </form>
                        <?php
                        }
                        ?>
                        
                        
                    </div>
                </div>    
            </tbody>
            </table>
        </div>
                    
                </div>
            </div>


        </div>

    </div>

</div>
</div>
<script type="text/javascript">
    $("#cancel").click(function()
    {
        window.location.href= "<?php echo $this->basePath()?>/admin/employee/add";
    });

</script>