<script type="text/javascript">
    //Status off
    $('.ston').live('click',function()
    {
        var offId = $(this).attr('id'); 
        
        $.ajax({
            type:"POST",
            url:"/admin/rowmaterial/statusOff",
            cache:false,
            data:{ offId:offId },
            dataType:"html",
            success:function(data)
            {
                $("#msg").html(data);
                location.reload();
            }
        });

    });

    //Status On
    $('.stof').live('click',function()
    {
        var onId = $(this).attr('id'); 
        
        $.ajax({
            type:"POST",
            url:"/admin/rowmaterial/statusOn",
            cache:false,
            data:{ onId:onId },
            dataType:"html",
            success:function(data)
            {
                $("#msg").html(data);
                location.reload();
                
            }
        });

    });
</script>
<div class="span9" id="content">
    <div class="row-fluid">
        <div class="span12">

            <!-- block - -->

            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Rowmaterilal Form</div>
                    <span style="font-size:12px;color:red; margin-left:520px; float:left;">
                        <div id="msg"></div>
                        <?php
                        if(count($flashMessages))
                        {
                            foreach ($flashMessages as $msg)
                            {
                                echo "<br>".$msg;   
                            }   
                        }
                        ?>
                    </span>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <form class="form-horizontal" id="addRowmaterilal" name="addRowmaterilal" method="post" enctype="multipart/form-data">
                            <fieldset>
                                <legend>Form Components</legend>
                               
                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Category </label>
                                    <div class="controls">
                                        <select id="category" name="category" required>
                                            <option value="">Select category</option>
                                            <?php 
                                            foreach ($categories as $key => $value)
                                            {
                                                echo '<option value="'.$value['id'].'">'.$value['category'].'</option>';
                                            }                       
                                            ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Rowmateril Name</label>
                                    <div class="controls">
                                        <input type="text" name="rowmaterial" id="rowmaterial" class="span6" required>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Rowmateril Code</label>
                                    <div class="controls">
                                        <input type="text" name="code" id="code" class="span6" required >
                                    </div>
                                </div>
                                <?php /*<div class="control-group">
                                    <label class="control-label" for="typeahead">Unit Of Measure </label>
                                    <div class="controls">
                                        <select id="uom" name="uom" required>
                                            <option value="">Selct Unit Of Measure</option>
                                            <?php 
                                            foreach ($uom as $key => $value)
                                            {
                                                echo '<option value="'.$value['id'].'">'.$value['uom'].'</option>';
                                            }                       
                                            ?>
                                        </select>
                                    </div>
                                </div>*/?>

                                <div class="form-actions">
                                    <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                    <button type="reset" class="btn" id="cancel">Cancel</button>
                                </div>
                            </fieldset>
                        </form>
                        
                    </div>
                </div>
                <div class="navbar navbar-inner block-header">
                    <div class="block-content collapse in">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Category</th>
                                    <th>Item</th>
                                    <th>Item Code</th>
                                    <th>Uom</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                        <tbody>
                    <?php
                    $cnt= count($fetchAllDatas);
                    if($cnt != '')
                    {
                        foreach ($fetchAllDatas as $key => $value)
                        {
                        ?>                         
                            <tr>
                                <td><?php echo $value['id'];?></td>
                                <td><?php echo $value['category']; ?></td>
                                <td><?php echo $value['item']; ?></td>
                                <td><?php echo $value['item_code']; ?></td>
                                <td><?php echo $value['uom']; ?></td>

                                <td><?php 

                                    if($value['status'] == 1)
                                    {
                                    ?>
                                        <img src="/images/on.png" border="0" width="20" height="20" id="<?php echo $value['id']; ?>" class="ston">
                                    <?php
                                    }
                                    else 
                                    {
                                        ?>
                                        <img src="/images/off.png" border="0" width="20" height="20" id="<?php echo $value['id']; ?>" class="stof">
                                        <?php
                                    }
                                    ?>
                                </td>

                                <td>
                                    <a href="/admin/rowmaterial/edit/<?php echo $value['id']; ?>" style="text-decoration:none;"><img src="/images/edit.png" border="0" width="20" height="20"></a>
                                </td>
                                <!--<td>
                                    <img src="/images/delete.png" id="<?php echo $value['id']; ?>" border="0" width="20" height="20" class="del" />
                                </td>-->
                            </tr>
                        <?php
                        }
                    }
                    else
                    {
                        echo "<tr><td colspan='7'>Oops there is no records...</td></tr>";
                    }
                    ?>
                        <tr><td colspan="6">
                    <div align="center"><?php echo $this->paginationControl($this->fetchAllDatas, 'Elastic', 'pagination.phtml'); ?></div></td></tr>
            </tbody>
            </table>
        </div>
                    
                </div>
            </div>


        </div>

    </div>

</div>
</div>
<script type="text/javascript">
    $("#cancel").click(function()
    {
        window.location.href= "<?php echo $this->basePath()?>/admin/category/add";
    });

</script>