
<div class="span9" id="content">
    <div class="row-fluid">
        <div class="span12">

            <!-- block - -->

            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Rowmaterilal Form</div>
                    <span style="font-size:12px;color:red; margin-left:520px; float:left;">
                        <div id="msg"></div>
                        <?php
                        if(count($flashMessages))
                        {
                            foreach ($flashMessages as $msg)
                            {
                                echo "<br>".$msg;   
                            }   
                        }
                        ?>
                    </span>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <?php
                        foreach ($fetchAllDatas as $value)
                        {
                                                    ?>
                        <form class="form-horizontal" id="addRowmaterilal" name="addRowmaterilal" method="post" enctype="multipart/form-data">
                            <fieldset>
                                <legend>Form Components</legend>
                               
                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Category </label>
                                    <div class="controls">
                                        <select id="category" name="category" required>
                                            <option value="">Select category</option>
                                            <?php 
                                            foreach ($categories as $key => $values)
                                            {
                                            ?>
                                                <option value="<?php echo $values['id']?>" <?php if($value['category_id']== $values['id']) echo "selected";?> > <?php echo $values['category']?></option>
                                            <?php
                                            }                       
                                            ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Rowmateril Name</label>
                                    <div class="controls">
                                        <input type="text" name="rowmaterial" id="rowmaterial" class="span6" value="<?php echo $value['item'];?>" required>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Rowmateril Code</label>
                                    <div class="controls">
                                        <input type="text" name="code" id="code" class="span6" value="<?php echo $value['item_code'];?>" required >
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Unit Of Measure </label>
                                    <div class="controls">
                                        <select id="uom" name="uom" required>
                                            <option value="">Selct Unit Of Measure</option>
                                            <?php 
                                            foreach ($uom as $key => $values1)
                                            {
                                                ?>
                                                <option value="<?php echo $values1['id']?>" <?php if($value['uom']== $values1['id']) echo "selected";?> > <?php echo $values1['uom']?></option>
                                            <?php
                                            }                       
                                            ?>
                                        </select>
                                    </div>
                                </div>

                                <div class="form-actions">
                                    <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                    <button type="reset" class="btn" id="cancel">Cancel</button>
                                </div>
                            </fieldset>
                        </form>
                        <?php
                        }
                        ?>
                        
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</div>

</div>
</div>
<script type="text/javascript">
    $("#cancel").click(function()
    {
        window.location.href= "<?php echo $this->basePath()?>/admin/rowmaterial/add";
    });

</script>