<script type="text/javascript">
    //Status off
    $('.ston').live('click',function()
    {
        var offId = $(this).attr('id'); 
        
        $.ajax({
            type:"POST",
            url:"/admin/rowmaterial/statusOff",
            cache:false,
            data:{ offId:offId },
            dataType:"html",
            success:function(data)
            {
                $("#msg").html(data);
                location.reload();
            }
        });

    });

    //Status On
    $('.stof').live('click',function()
    {
        var onId = $(this).attr('id'); 
        
        $.ajax({
            type:"POST",
            url:"/admin/rowmaterial/statusOn",
            cache:false,
            data:{ onId:onId },
            dataType:"html",
            success:function(data)
            {
                $("#msg").html(data);
                location.reload();
                
            }
        });

    });
    
    
    $('#plus').live('click',function()
    {
        $.ajax({
            type:"POST",
            url:"/admin/ingredient/ajaxTable",
            cache:false,
            dataType:"html",
            success:function(data)
            {
                $("#ajx_table").append(data);   
            }
        });

    });
    
    $('#close').live('click',function()
    {
        alert("haii");
        $("#cp").hide();
    });
    function getMaterialId(materialId)
    {
        var mid= materialId;
        $('#hid').val(mid);
        $.ajax({
            type: "POST",
            url : "/admin/ingredient/uom",
            cashe : false,
            data : {mid:mid},
            dataType: 'html',
            success: function (data) {
                $('#uom').val(data);
            }
        });
        
    }
    
    function getQuantity(val)
    {
        //alert(val);
        var quan= val;
        var matId=  $('#hid').val();
        //alert(matId);
        //alert(quan);
        $.ajax({
            type: "POST",
            url : "/admin/ingredient/prize",
            cashe : false,
            data : { matId:matId, quan:quan},
            dataType: 'html',
            success: function (data) {
                $('#rate').val(data);
            }
        });
    }
    
    
</script>
<div class="span99" id="content">
    <div class="row-fluid">
        <div class="span12">

            <!-- block - -->

            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Product Ingredients Form</div>
                    <span style="font-size:12px;color:red; margin-left:520px; float:left;">
                        <div id="msg"></div>
                        <?php
                        if(count($flashMessages))
                        {
                            foreach ($flashMessages as $msg)
                            {
                                echo "<br>".$msg;   
                            }   
                        }
                        ?>
                    </span>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <form class="form-horizontal" id="addRowmaterilal" name="addRowmaterilal" method="post" enctype="multipart/form-data">
                            <fieldset>
                                <legend>Form Components</legend>
                               
                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Product </label>
                                    <div class="controls">
                                        <select id="category" name="category" required>
                                            <option value="">Select Product</option>
                                            <?php 
                                            foreach ($products as $key => $value)
                                            {
                                                echo '<option value="'.$value['id'].'">'.$value['product'].'</option>';
                                            }                       
                                            ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="control-group">Ingredients</div>
                                <div class="control-group">
                                    <div class="controls" style="margin-left: 0;">
                                        <table border="0">
                                            <th style="width:220px;">Row Material</th>
                                            <th style="width:220px;">Quantity</th>
                                            <th style="width:220px;">Uom</th>
                                            <th style="width:220px;">Rate</th>
                                        </table>
                                    </div>
                                </div>                              
                                <div id="ajx_table"></div>
                                <div class="control-group">
                                    <div class="controls" style="float:right;">
                                        <img src="/images/plus.png" border="0" id="plus">
                                    </div>
                                </div>   
                                
                                <div class="form-actions">
                                    <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                    <button type="reset" class="btn" id="cancel">Cancel</button>
                                </div>
                            </fieldset>
                        </form>
                        
                    </div>
                </div>
                <div class="navbar navbar-inner block-header">
                    <div class="block-content collapse in">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Category</th>
                                    <th>Item</th>
                                    <th>Item Code</th>
                                    <th>Uom</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                        <tbody>
                    <?php
                    $cnt= count($fetchAllDatas);
                    if($cnt != '')
                    {
                        foreach ($fetchAllDatas as $key => $value)
                        {
                        ?>                         
                            <tr>
                                <td><?php echo $value['id'];?></td>
                                <td><?php echo $value['category']; ?></td>
                                <td><?php echo $value['item']; ?></td>
                                <td><?php echo $value['item_code']; ?></td>
                                <td><?php echo $value['uom']; ?></td>

                                <td><?php 

                                    if($value['status'] == 1)
                                    {
                                    ?>
                                        <img src="/images/on.png" border="0" width="20" height="20" id="<?php echo $value['id']; ?>" class="ston">
                                    <?php
                                    }
                                    else 
                                    {
                                        ?>
                                        <img src="/images/off.png" border="0" width="20" height="20" id="<?php echo $value['id']; ?>" class="stof">
                                        <?php
                                    }
                                    ?>
                                </td>

                                <td>
                                    <a href="/admin/rowmaterial/edit/<?php echo $value['id']; ?>" style="text-decoration:none;"><img src="/images/edit.png" border="0" width="20" height="20"></a>
                                </td>
                                <!--<td>
                                    <img src="/images/delete.png" id="<?php echo $value['id']; ?>" border="0" width="20" height="20" class="del" />
                                </td>-->
                            </tr>
                        <?php
                        }
                    }
                    else
                    {
                        echo "<tr><td colspan='7'>Oops there is no records...</td></tr>";
                    }
                    ?>
                        <tr><td colspan="6">
                    <div align="center"><?php echo $this->paginationControl($this->fetchAllDatas, 'Elastic', 'pagination.phtml'); ?></div></td></tr>
            </tbody>
            </table>
        </div>
                    
                </div>
            </div>


        </div>

    </div>

</div>
</div>
<script type="text/javascript">
    $("#cancel").click(function()
    {
        window.location.href= "<?php echo $this->basePath()?>/admin/category/add";
    });

</script>