<div class="control-group" id="cp<?php echo $this->count ;?>">
    <div class="controls" style="margin-left: 0;">
        <table border="0">
            <tr>
                <td>
                    
                    <input type="hidden" id="hid" >
                    <input type="hidden" id="hidQuan">
                </td>
            </tr>
            <tr>
                <td>
                    <select id="product" name="product[]" onChange="getMaterialId(this.value)" required>
                        <option value="">Select Product</option>
                        <?php 
                        foreach ($rowmaterial as $key => $value)
                        {
                            echo '<option value="'.$value['id'].'">'.$value['item'].'</option>';
                        }                       
                        ?>
                    </select>
                </td>
                <td>
                    <input type="text" name="quantity[]" id="quantity<?php echo $this->count ;?>"onchange="getQuantity(this.value)" required>
                </td>
                <td>
                    <input type="text" name="uom[]" id="uom<?php echo $this->count ;?>" readonly required>
                </td>
                <td>
                    <input type="text" name="rate[]" id="rate<?php echo $this->count ;?>" readonly required>
                </td>
                <td><img src="/images/minus.png" border="0" title="delete" id="close_<?php echo $this->count ;?>" class="cls"></td>
            </tr>
        </table>
    </div>
</div>