<script type="text/javascript">

    
    $(document).ready(function() {
        showTable();

    });
    
    function showTable()
    {
        
        $.ajax({

            type:"POST",
            url:"/agentSuperAdmin/commonSettings/ajaxList",
            cache:false,
            data:{},
            dataType:"html",
            success:function(data)
            {
                $("#ajx_table").html(data);
            }
        });
    }

       
    
    //Status off
    $('.ston').live('click',function()
    {
        var offId = $(this).attr('id'); 
        $.ajax({
            type:"POST",
            url:"/agentSuperAdmin/commonSettings/status",
            cache:false,
            data:{offId:offId },
            dataType:"html",
            success:function(data)
            {
                $("#msg").html(data);
                showTable();
            }
        });

    });

    //Status On
    $('.stof').live('click',function()
    {
        var onId = $(this).attr('id'); 
        $.ajax({
            type:"POST",
            url:"/agentSuperAdmin/commonSettings/status",
            cache:false,
            data:{ onId:onId },
            dataType:"html",
            success:function(data)
            {
                $("#msg").html(data);
                showTable();
            }
        });

    });

   


</script>




<style type="text/css">
    .ston { cursor: pointer;} .stof { cursor: pointer;} .del { cursor: pointer;}

</style>

<div class="span9" id="content">
    <div class="row-fluid">
      	<div class="navbar">
           	
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left" style="text-align:center; float: left; width:100%;">Common Settings</div>
                    
                </div>
                <div id="ajx_table"></div>
            </div>
        </div>
    </div>
                 