<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Cooolwebsite'))?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600' rel='stylesheet' type='text/css'>
        <?php 
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon/favicon.png'))
                              ->prependStylesheet($this->basePath() . '/css/style.css')
                             ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                             ->prependStylesheet($this->basePath() . '/css/prettyPhoto.css')
                             ->prependStylesheet($this->basePath() . '/css/flexslider.css')
                             ->prependStylesheet($this->basePath() . '/css/font-awesome.css')
                             ->prependStylesheet($this->basePath() . '/css/slider.css')
                             ->prependStylesheet($this->basePath() . '/css/parallax-slider.css')
                             ->prependStylesheet($this->basePath() . '/css/red.css')
                             ->prependStylesheet($this->basePath() . '/css/styleswitch.css');
         
        ?>
        
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/bootstrap.js')
            ->prependFile($this->basePath() . '/js/jquery.easing.1.3.js')
            ->prependFile($this->basePath() . '/js/app.js')
            ->prependFile($this->basePath() . '/js/index.js')
            ->prependFile($this->basePath() . '/js/optionspanel.js')
            ->prependFile($this->basePath() . '/js/filter.js')
            ->prependFile($this->basePath() . '/js/jquery.isotope.js')
            ->prependFile($this->basePath() . '/js/jquery.prettyPhoto.js')
            ->prependFile($this->basePath() . '/js/jquery.flexslider-min.js')
            ->prependFile($this->basePath() . '/js/jquery.refineslide.min.js')
            ->prependFile($this->basePath() . '/js/jquery.cslider.js')
            ->prependFile($this->basePath() . '/js/modernizr.custom.28468.js')
            ->prependFile($this->basePath() . '/js/custom.js')
            ->prependFile($this->basePath() . '/js/jquery.form.js');
        ?>
    </head>
    <script type="text/javascript">
        jQuery(document).ready(function() {
            App.init();
            App.initSliders();
            Index.initParallaxSlider();
        });
    </script>
    <script type="text/javascript">
        $(function()
        {
            var url = window.location.href; 
            $("#nav_main a").each(function()
            {
                if(url == (this.href))
                { 
                    $(this).closest("li a").addClass("active");
                }
            });
        });
    </script>
    <body>
    <div id="wrapper">
      <div class="top"></div>
      <header>
          <div class="container">
              <div class="row">
                  <div class="col-md-12">
                      <div class="header-text">
                          <!-- LOGO -->
                              <h3>Your Logo<span class="grey"> Here</span></h3>
                              <p>product of codexmind</p>
                          <!-- LOGO -->
                      </div>
                  </div>
              </div>
          </div>
      </header>
      <div class="sep"></div>
      <div class="navbar bs-docs-nav" role="banner">
          <div class="container">
              <div class="navbar-header">
                  <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                  </button>
              </div>
            
              <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
                  <ul class="nav navbar-nav" id="nav_main">
                      <?php
                      foreach ($listAllMenuDatas as $key => $value)
                      {
                          if($value['admin_page'] == 'Home')
                          {
                          ?>
                              <li><a href="<?php if($value['url'] != ''){ echo $value['url'];} else {echo "#";}?>"><i class="icon-home"></i></a></li>
                          <?php
                          }
                          else if($value['admin_page'] != 'Home')
                          {         
                          ?>
                          <li><a href="<?php if($value['url'] != ''){ echo $value['url'];} else {echo "#";}?>"><?php if($value['menu_name'] != '') {echo ucfirst($value['menu_name']); } else{ echo "";}?></a></li>
                          <?php
                          }
                      }
                      ?>
                  </ul>
              </nav>
          </div>
      </div>
      <div class="sep"></div>
      <div class="container11">
          <?php echo $this->content; ?>
      </div>

      <!-- Footer starts -->
      <footer>
        <div class="container">
          <div class="row">
            <div class="col-md-12">
                  <!-- Copyright info -->
                  <p class="copy">Product of Codex mind</p>
            </div>
          </div>
        <div class="clearfix"></div>
        </div>
      </footer>
      <!-- Footer ends -->

      <!-- Scroll to top -->
      <span class="totop"><a href="#"><i class="icon-chevron-up"></i></a></span>
          <?php echo $this->inlineScript() ?>
  </div>
  </body>
</html>